apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tusky-prod

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: tusky-docs
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: docs.tusky.io
      - op: replace
        path: /spec/rules/0/host
        value: docs.tusky.io
      - op: replace
        path: /spec/tls/0/secretName
        value: tusky-docs-prod-tls
  - target:
      kind: Deployment
      name: tusky-docs
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2

images:
  - name: tusky-docs
    newName: ghcr.io/tusky-io/docs
    newTag: prod-latest
