apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tusky-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: tusky-docs
      $patch: delete
  - target:
      kind: Service
      name: tusky-docs
    patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
  - target:
      kind: Deployment
      name: tusky-docs
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: tusky-docs
    newName: ghcr.io/tusky-io/docs
    newTag: dev-latest
