apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tusky-dev

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: tusky-docs
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: docs-dev.tusky.io
      - op: replace
        path: /spec/rules/0/host
        value: docs-dev.tusky.io
      - op: replace
        path: /spec/tls/0/secretName
        value: tusky-docs-dev-tls
  - target:
      kind: Deployment
      name: tusky-docs
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: tusky-docs
    newName: ghcr.io/tusky-io/docs
    newTag: dev-latest
